### ISSUE TITLE
No, its joke

### ISSUE THREAD

**Issue by GuckTubeYT** [BlackGhostGT/CoreDataBuilder-3.51-#1]
Report this

**Comment by BlackGhostGT** [comment]
Stop being retarded, You are saying i used to steal ur discord token? It doesnt even contain any discord activities. You are doing this because u made ur own and u don't want to publish it for public since you are selfish.

**Comment by GuckTubeYT** [comment]
Ok okay lol, no no im just kidding

**Comment by GuckTubeYT** [comment]
This application not a virus and not a token stealer (i hope)
